<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Enrollment Reports</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'DejaVu Sans', Arial, sans-serif;
            font-size: 11px;
            color: #333;
            line-height: 1.4;
        }

        .header {
            text-align: center;
            margin-bottom: 30px;
            padding-bottom: 15px;
            border-bottom: 3px solid #1b5e20;
        }

        .header h1 {
            font-size: 20px;
            color: #1b5e20;
            margin-bottom: 5px;
            font-weight: bold;
        }

        .header h2 {
            font-size: 14px;
            color: #666;
            font-weight: normal;
        }

        .info-section {
            margin-bottom: 20px;
            padding: 10px;
            background-color: #f5f5f5;
            border-left: 4px solid #1b5e20;
        }

        .info-row {
            display: table;
            width: 100%;
            margin-bottom: 8px;
        }

        .info-label {
            display: table-cell;
            width: 150px;
            font-weight: bold;
            color: #555;
        }

        .info-value {
            display: table-cell;
            color: #333;
        }

        .stats-section {
            margin-bottom: 25px;
        }

        .stats-grid {
            display: table;
            width: 100%;
            border-collapse: collapse;
        }

        .stats-cell {
            display: table-cell;
            padding: 12px;
            text-align: center;
            border: 1px solid #ddd;
            background-color: #f9f9f9;
        }

        .stats-label {
            font-size: 10px;
            color: #666;
            margin-bottom: 5px;
            text-transform: uppercase;
        }

        .stats-value {
            font-size: 18px;
            font-weight: bold;
            color: #1b5e20;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        th {
            background-color: #1b5e20;
            color: white;
            padding: 8px 6px;
            text-align: left;
            font-size: 9px;
            font-weight: bold;
            text-transform: uppercase;
            border: 1px solid #0d4e14;
        }

        td {
            padding: 6px;
            border: 1px solid #ddd;
            font-size: 9px;
            vertical-align: top;
        }

        tr:nth-child(even) {
            background-color: #f9f9f9;
        }

        tr:nth-child(odd) {
            background-color: #ffffff;
        }

        .footer {
            margin-top: 30px;
            padding-top: 15px;
            border-top: 1px solid #ddd;
            text-align: center;
            font-size: 9px;
            color: #666;
        }

        .page-break {
            page-break-after: always;
        }

        .text-center {
            text-align: center;
        }

        .text-right {
            text-align: right;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>OPOL NATIONAL SECONDARY TECHNICAL SCHOOL</h1>
        <h2>Enrollment Reports</h2>
    </div>

    <div class="info-section">
        <div class="info-row">
            <span class="info-label">Strand:</span>
            <span class="info-value">{{ $filters['strand'] ?? 'All Strands' }}</span>
        </div>
        <div class="info-row">
            <span class="info-label">School Year:</span>
            <span class="info-value">{{ $filters['school_year'] ?? 'All School Years' }}</span>
        </div>
        <div class="info-row">
            <span class="info-label">Semester:</span>
            <span class="info-value">{{ $filters['semester'] ?? 'All Semesters' }}</span>
        </div>
        <div class="info-row">
            <span class="info-label">Status:</span>
            <span class="info-value">{{ $filters['status'] ?? 'All Statuses' }}</span>
        </div>
        <div class="info-row">
            <span class="info-label">Generated By:</span>
            <span class="info-value">{{ $generated_by ?? 'N/A' }}</span>
        </div>
        <div class="info-row">
            <span class="info-label">Generated At:</span>
            <span class="info-value">{{ $generated_at ?? 'N/A' }}</span>
        </div>
    </div>

    <div class="stats-section">
        <div class="stats-grid">
            <div class="stats-cell">
                <div class="stats-label">Total</div>
                <div class="stats-value">{{ $stats['total'] ?? 0 }}</div>
            </div>
            <div class="stats-cell">
                <div class="stats-label">Pre-Enrolled</div>
                <div class="stats-value">{{ $stats['pre_enrolled'] ?? 0 }}</div>
            </div>
            <div class="stats-cell">
                <div class="stats-label">Recommended</div>
                <div class="stats-value">{{ $stats['recommended'] ?? 0 }}</div>
            </div>
            <div class="stats-cell">
                <div class="stats-label">Enrolled</div>
                <div class="stats-value">{{ $stats['enrolled'] ?? 0 }}</div>
            </div>
            <div class="stats-cell">
                <div class="stats-label">Rejected</div>
                <div class="stats-value">{{ $stats['rejected'] ?? 0 }}</div>
            </div>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 5%;">#</th>
                <th style="width: 20%;">Student Name</th>
                <th style="width: 10%;">LRN</th>
                <th style="width: 15%;">Strand</th>
                <th style="width: 12%;">School Year</th>
                <th style="width: 10%;">Semester</th>
                <th style="width: 10%;">Status</th>
                <th style="width: 10%;">Processed By</th>
                <th style="width: 8%;">Date</th>
            </tr>
        </thead>
        <tbody>
            @forelse($enrollments as $index => $enrollment)
                <tr>
                    <td class="text-center">{{ $index + 1 }}</td>
                    <td>{{ $enrollment['student_name'] }}</td>
                    <td>{{ $enrollment['lrn'] }}</td>
                    <td>{{ $enrollment['strand'] }} ({{ $enrollment['strand_code'] }})</td>
                    <td>{{ $enrollment['school_year'] }}</td>
                    <td>{{ $enrollment['semester'] }}</td>
                    <td>{{ $enrollment['status'] }}</td>
                    <td>{{ $enrollment['processed_by'] }}</td>
                    <td>{{ $enrollment['date'] }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="9" class="text-center" style="padding: 20px;">
                        No enrollment records found for the selected filters.
                    </td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        <p>This report was generated on {{ $generated_at ?? now()->format('F d, Y h:i A') }}</p>
        <p>OPOL NATIONAL SECONDARY TECHNICAL SCHOOL - Student Management System</p>
    </div>
</body>
</html>

