<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Complete Analytics Report</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 9px; color: #333; margin: 0; padding: 15px; }
        .header { text-align: center; margin-bottom: 15px; border-bottom: 3px solid #000825; padding-bottom: 8px; }
        .header h1 { margin: 0; font-size: 18px; color: #000825; font-weight: bold; }
        .header h2 { margin: 5px 0; font-size: 12px; color: #555; }
        .info-section { margin: 10px 0; padding: 8px; background-color: #f8f9fa; border-radius: 4px; }
        .section { margin: 20px 0; page-break-inside: avoid; }
        .section-title { font-size: 14px; font-weight: bold; color: #000825; margin-bottom: 10px; border-bottom: 2px solid #000825; padding-bottom: 5px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th { background-color: #000825; color: white; padding: 6px; text-align: left; font-size: 8px; font-weight: bold; }
        td { padding: 5px 6px; border-bottom: 1px solid #e2e8f0; font-size: 8px; }
        tr:nth-child(even) { background-color: #f8f9fa; }
        .footer { margin-top: 20px; padding-top: 8px; border-top: 1px solid #ccc; font-size: 8px; color: #666; text-align: center; }
    </style>
</head>
<body>
    <div class="header">
        <h1>WESMG SYSTEM</h1>
        <h2>COMPLETE ANALYTICS REPORT</h2>
    </div>
    <div class="info-section">
        <strong>School Year:</strong> {{ $school_year }} | <strong>Semester:</strong> {{ $semester }} | <strong>Generated:</strong> {{ $generated_at }}
    </div>
    
    <div class="section">
        <div class="section-title">Enrollment Statistics</div>
        <table>
            <tr><td><strong>Total Enrollments:</strong></td><td>{{ $enrollmentStats['total'] ?? 0 }}</td></tr>
            <tr><td><strong>Enrolled:</strong></td><td>{{ $enrollmentStats['enrolled'] ?? 0 }}</td></tr>
            <tr><td><strong>Pre-Enrolled:</strong></td><td>{{ $enrollmentStats['pre_enrolled'] ?? 0 }}</td></tr>
            <tr><td><strong>Recommended:</strong></td><td>{{ $enrollmentStats['recommended'] ?? 0 }}</td></tr>
            <tr><td><strong>Rejected:</strong></td><td>{{ $enrollmentStats['rejected'] ?? 0 }}</td></tr>
        </table>
    </div>

    <div class="section">
        <div class="section-title">Academic Statistics</div>
        <table>
            <tr><td><strong>Total Faculty:</strong></td><td>{{ $academicStats['faculty'] ?? 0 }}</td></tr>
            <tr><td><strong>Sections:</strong></td><td>{{ $academicStats['sections'] ?? 0 }}</td></tr>
            <tr><td><strong>Subjects:</strong></td><td>{{ $academicStats['subjects'] ?? 0 }}</td></tr>
            <tr><td><strong>Classes:</strong></td><td>{{ $academicStats['classes'] ?? 0 }}</td></tr>
        </table>
    </div>

    <div class="section">
        <div class="section-title">Enrollment by Strand</div>
        <table>
            <thead>
                <tr>
                    <th>Strand</th>
                    <th>Code</th>
                    <th>Count</th>
                </tr>
            </thead>
            <tbody>
                @forelse($enrollmentByStrand as $strand)
                <tr>
                    <td>{{ $strand->Strand_name ?? 'Unassigned' }}</td>
                    <td>{{ $strand->Strand_code ?? 'N/A' }}</td>
                    <td>{{ $strand->count }}</td>
                </tr>
                @empty
                <tr><td colspan="3" style="text-align: center;">No data available</td></tr>
                @endforelse
            </tbody>
        </table>
    </div>

    <div class="section">
        <div class="section-title">Gender Distribution</div>
        <table>
            <tr><td><strong>Male:</strong></td><td>{{ $analytics['gender_distribution']['male'] ?? 0 }}</td></tr>
            <tr><td><strong>Female:</strong></td><td>{{ $analytics['gender_distribution']['female'] ?? 0 }}</td></tr>
            <tr><td><strong>Total Students:</strong></td><td>{{ $analytics['total_students'] ?? 0 }}</td></tr>
        </table>
    </div>

    <div class="footer">Generated by WESMG System on {{ $generated_at }}</div>
</body>
</html>

