<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Sections Report</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 10px; color: #333; margin: 0; padding: 20px; }
        .header { text-align: center; margin-bottom: 15px; border-bottom: 3px solid #000825; padding-bottom: 8px; }
        .header h1 { margin: 0; font-size: 18px; color: #000825; font-weight: bold; }
        .header h2 { margin: 5px 0; font-size: 12px; color: #555; }
        .info-section { margin: 10px 0; padding: 8px; background-color: #f8f9fa; border-radius: 4px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th { background-color: #000825; color: white; padding: 8px; text-align: left; font-size: 9px; font-weight: bold; }
        td { padding: 6px 8px; border-bottom: 1px solid #e2e8f0; font-size: 9px; }
        tr:nth-child(even) { background-color: #f8f9fa; }
        .footer { margin-top: 20px; padding-top: 8px; border-top: 1px solid #ccc; font-size: 9px; color: #666; text-align: center; }
    </style>
</head>
<body>
    <div class="header">
        <h1>WESMG SYSTEM</h1>
        <h2>SECTIONS REPORT</h2>
    </div>
    <div class="info-section">
        <strong>School Year:</strong> {{ $school_year }} | <strong>Semester:</strong> {{ $semester }} | <strong>Total Sections:</strong> {{ $total_sections }} | <strong>Generated:</strong> {{ $generated_at }}
    </div>
    <table>
        <thead>
            <tr>
                <th>Section Name</th>
                <th>Strand</th>
                <th>Adviser</th>
                <th>Students</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse($sections as $section)
            <tr>
                <td>{{ $section['section_name'] }}</td>
                <td>{{ $section['strand'] }}</td>
                <td>{{ $section['adviser'] }}</td>
                <td>{{ $section['student_count'] }}</td>
                <td>{{ $section['is_active'] ? 'Active' : 'Inactive' }}</td>
            </tr>
            @empty
            <tr><td colspan="5" style="text-align: center; padding: 15px;">No sections data available</td></tr>
            @endforelse
        </tbody>
    </table>
    <div class="footer">Generated by WESMG System on {{ $generated_at }}</div>
</body>
</html>

